id = lab-tacacs

key = "labkey123"

accounting file = /var/log/tac_plus.acct

# Groups
group = netadmins {
    default service = permit
    service = exec {
        priv-lvl = 15
    }
}

group = readonly {
    default service = deny
    service = exec {
        priv-lvl = 1
    }
    cmd = show {
        permit .*
    }
    cmd = enable {
        permit .*
    }
}

# Users
user = alice {
    member = netadmins
    pap = cleartext "AlicePass!"
    login = cleartext "AlicePass!"
}

user = bob {
    member = readonly
    pap = cleartext "BobPass!"
    login = cleartext "BobPass!"
}
