frr defaults traditional
hostname backend2
!
router bgp 65020
 bgp router-id 10.0.2.10
 no bgp ebgp-requires-policy
 neighbor 10.0.2.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.99.99.1/32
  neighbor 10.0.2.1 activate
 exit-address-family
!
line vty
!
