frr defaults traditional
hostname backend3
!
router bgp 65030
 bgp router-id 10.0.3.10
 no bgp ebgp-requires-policy
 neighbor 10.0.3.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.99.99.1/32
  neighbor 10.0.3.1 activate
 exit-address-family
!
line vty
!
